id: sync_from_git
namespace: company.team

tasks:
  - id: sync_flows
    type: io.kestra.plugin.git.Sync
    url: https://github.com/ChiaXinLiang/marcus-kestra-script.git
    branch: company-team
    username: marcus
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    dryRun: false

  - id: sync_files
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/ChiaXinLiang/marcus-kestra-script.git
    branch: company-team
    username: marcus
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    gitDirectory: _files
    dryRun: false

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: testtest123123

    # To set up GitHub webhook:
    # 1. Go to your GitHub repository
    # 2. Click "Settings" tab
    # 3. Click "Webhooks" in left sidebar
    # 4. Click "Add webhook"
    # 5. Set Payload URL to your Kestra webhook URL (e.g. https://your-kestra-url/api/v1/webhooks/git/{namespace}/{flowId})
    # 6. Set Content type to "application/json"
    # 7. Set Secret to match the value in GITHUB_WEBHOOK_SECRET
    # 8. Select "Just the push event" under events
    # 9. Click "Add webhook"
