id: sync_from_git
namespace: company.team

tasks:
  - id: sync_flows
    type: io.kestra.plugin.git.SyncFlows
    gitDirectory: _flows # optional; set to _flows by default
    targetNamespace: company.team # required
    includeChildNamespaces: true # optional; by default, it's set to false to allow explicit definition
    delete: true # optional; by default, it's set to false to avoid destructive behavior
    url: https://github.com/ChiaXinLiang/marcus-kestra-script.git # required
    branch: company-team
    username: marcus
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    dryRun: false # if true, the task will only log which flows from Git will be added/modified or deleted in kestra without making any changes in kestra backend yet

  - id: sync_files
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/ChiaXinLiang/marcus-kestra-script.git
    delete: true
    branch: company-team
    username: marcus
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    gitDirectory: _files
    dryRun: false

triggers:
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"

    # To set up GitHub webhook:
    # 1. Go to your GitHub repository
    # 2. Click "Settings" tab
    # 3. Click "Webhooks" in left sidebar
    # 4. Click "Add webhook"
    # 5. Set Payload URL to your Kestra webhook URL (e.g. https://your-kestra-url/api/v1/webhooks/git/{namespace}/{flowId})
    # 6. Set Content type to "application/json"
    # 7. Set Secret to match the value in GITHUB_WEBHOOK_SECRET
    # 8. Select "Just the push event" under events
    # 9. Click "Add webhook"
    # Example webhook curl command:
