id: git_clone
namespace: prod

tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.PushFlows
    username: marcus
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    url: "https://github.com/ChiaXinLiang/marcus-kestra-script"
    branch: main
    sourceNamespace: company.team
    targetNamespace: prod
    gitDirectory: flows
    commitMessage: "Automated push: {{ now() }}"
    includeChildNamespaces: true

triggers:
  - id: schedule_push
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"
