id: sync_from_git
namespace: prod

tasks:
  - id: git
    type: io.kestra.plugin.git.Sync
    url: https://github.com/ChiaXinLiang/marcus-kestra-script.git
    branch: main
    username: marcus
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    gitDirectory: "_flows"  # Add this line
    dryRun: true  # if true, print the output of what files will be added/modified or deleted without overwriting the files yet

triggers:
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"