id: weaviate-get
namespace: prod

tasks:
  - id: getWeaviateMovies
    type: io.kestra.plugin.weaviate.Query
    url: "{{ envs.weaviate_url }}"
    apiKey: "{{ secret('WEAVIATE_API_KEY') }}"
    query: |
      {
        Get {
          Movie {
            name,
            description,
            category
          }
        }
      }
      
  - id: return_results
    type: io.kestra.plugin.core.debug.Return
    format: "{{ outputs.getWeaviateMovies }}"

triggers:
  - id: webhook_trigger
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"
