id: webhook_flow
namespace: prod

tasks:
  - id: log_hello_world
    type: io.kestra.plugin.core.log.Log
    message: "Received data: {{ trigger.body }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8r
